name: Run VK to WP script

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          pip install requests
      - name: Run VK to WP script
        run: python scripts/import_vk_to_wp.py
        env:
          VK_TOKEN: ${{ secrets.VK_TOKEN }}
          WP_USERNAME: ${{ secrets.WP_USERNAME }}
          WP_PASSWORD: ${{ secrets.WP_PASSWORD }}
